### ISSUE TITLE
Como obtener el folio ?

### ISSUE THREAD

**Issue by Mexflubber** [APIHub-CdC/rcc-ficoscore-pld-new-client-python#2]
En los ejemplos de la clase ApiRccFicoScorePld todas las operaciones reciben un folio pero en los ejemplos esta en blanco

```python
try:
     folio = ""
```

**Comment by cdc-ricardo** [comment]
Hola @Mexflubber,

El folio se obtiene de la respuesta del método **api.retrieve_rcc()**, dicho método hace un POST al API con el JSON body especificado y si la solicitud es exitosa retorna el reporte de crédito y el folio del reporte.

<img width="553" alt="image" src="https://github.com/APIHub-CdC/rcc-ficoscore-pld-new-client-python/assets/109605093/75a58989-4f8a-47e3-868b-8b2ee8b39790">

Saludos
